### PR TITLE
Implement new designs for repository search and collections pages

### LINKED ISSUE #448: Use different color for selected facets
The current color does not have enough contrast.

### LINKED ISSUE #546: Browse all collections page design
I put the details in pink on the mockup itself. Thought it might be more straightforward, but let me know. 

https://www.figma.com/proto/GVfAxOKT1pSxqv1DGM72aD/ARCLight?page-id=0%3A1&type=design&node-id=235-132&viewport=-9127%2C153%2C1&t=tolZlbOe8y81XcGB-1&scaling=min-zoom&starting-point-node-id=6%3A85&mode=design

### LINKED ISSUE #565: Design - Collection home page
Design specs in mockup below. Let me know if you need more detail.

https://www.figma.com/file/GVfAxOKT1pSxqv1DGM72aD/ARCLight?type=design&node-id=6%3A122&mode=design&t=3h7BtB8QphzklMp5-1

### LINKED ISSUE #566: Design - Collection item page
https://www.figma.com/file/GVfAxOKT1pSxqv1DGM72aD/ARCLight?type=design&node-id=13%3A279&mode=design&t=yVur48PFvgiFGvcw-1

### LINKED ISSUE #567: Design - Browse collections in one repository
https://www.figma.com/file/GVfAxOKT1pSxqv1DGM72aD/ARCLight?type=design&node-id=62%3A86&mode=design&t=yVur48PFvgiFGvcw-1

### PR DESCRIPTION
**Pull request by marlo-longley**
Wuhoo! Very curious to get feedback on this.

Closes #565, closes #566, closes #567, closes #546, closes #448

I know we discussed as a group on my last layout PR, but I think I found a cleaner way to deal with the layout overrides. Thanks for taking a look. 

For reference, here are the links to Astrid's mockups:
[Repository search ](https://www.figma.com/file/GVfAxOKT1pSxqv1DGM72aD/ARCLight?type=design&node-id=62-86&mode=design&t=SPmLHJRTfwYTMpdZ-0
), [Collection](https://www.figma.com/file/GVfAxOKT1pSxqv1DGM72aD/ARCLight?type=design&node-id=13%3A279&mode=design&t=yVur48PFvgiFGvcw-1)

Screenshot 2024-05-07 at 17 09 09
~
Screenshot 2024-05-07 at 17 09 44

### CODE REVIEW

**Comment by taylor-steve** [comment]
@marlo-longley this is looking great, it really brings the site together. I went to each issue and compared Figma to what I've got running locally. I'm purely listing visual diffs here in case it is helpful. Many of these might be out of scope/in a different issue/an issue on my box/nits/etc. I did clobber assets/restart.

### Possible Regressions?
- Cards now have borders on the landing and `/repositories` page
- Landing page gradient is no longer full width

### 565: Collection Home
- Links with underlines in some places where the design doesn't use them (e.g., Collection Contents, Breadcrumbs, body)
- Collection sidebar: Content looks ever so slightly left of design (design seems to have Collection/Collection overview/Collection contents aligned)
- Collection sidebar: The design has an icon before "Collection"
- Collection headers and labels differ in size/spacing (e.g., Summary, Abstract). This might be a viewport issue, but the designs seem to have content further left. Also, not sure if this is intentional or not but in the design the headers aren't all uppercase.
- Bookmark border isn't squared off in design

### 566: Collection Item
- Links with underlines
- Headers/labels (e.g., Access and Use, Restrictions)
- Current item highlight has a border that isn't in the design
- Expand button differs (although I like the green)

### 567: Collections in Repository
- Breadcrumb link in search results has dotted underline, but is standard blue link in design
- *Really* not sure if this is in scope, but if the collection has a "view more/less" link it's still rendering in red. Easier to find when "grouped by collection".
Screenshot 2024-05-07 at 4 44 32 PM

### General Questions
- Are we doing the pager styling as a different issue?

**Comment by marlo-longley** [comment]
@taylor-steve this is SO helpful thank you for the detailed notes!

I will address them today and break out any remaining tickets. Then we could have a baseline of this merged PR to work from.

**Comment by marlo-longley** [comment]
@taylor-steve I think I addressed all your comments! I went through them 1 by 1 and hopefully didn't introduce any new regressions. Thanks again.

I will create separate issues for
- removing the colon from metadata labels 
- change layout of paginator to match designs (moving the "next" button)

**Comment by taylor-steve** [comment]
@marlo-longley you've addressed nearly everything! There's one issue to fix, the rest are minor or are thoughts/questions. I certainly wouldn't consider them blockers to getting this in.

### Issue:
- Horizontal scroll bar on landing page, possible x overflow?

### 565: Collection Home
- Sorry, I missed this the first time. The design has horizontal lines separating the main sections (e.g., before "Background")
- "Collection contents" links don't have underlines in the design (could do this in #596?)
- My understanding is our new default SUL styling is to apply `text-decoration: underline` on hover for standard links. Should we be doing that here/now?

Things we could ask @astridu about once it's on demo:
- To my eye, there's a bit more vertical space between the metadata sections in the design
- At small sizes, we might consider fully left aligning or centering the metadata labels. They're currently slightly offset. I'd definitely wait for #601 if we're addressing mobile at this point.
Screenshot 2024-05-08 at 4 37 28 PM

### 566: Collection Item
- Same link styling/horizontal line as above, otherwise it looks exactly like the design.

### 567: Collections in Repository
- I think this looks exactly like the design.

**Comment by marlo-longley** [comment]
@taylor-steve Thanks again. I just pushed up new work that should address all of your comments, including the ones you had suggested Astrid take a look at. Hopefully no new regressions! But I did look it over on desktop and mobile. The biggest change is centralizing the link underlining logic, good call.

**Review by taylor-steve — APPROVED** [review]

**Comment by astridu** [comment]
@marlo-longley @taylor-steve WOWOW!! This looks soooo good! (I am looking on demo so let me know if that's not the right place)
Just a couple refinements:
- As Steve mentioned, on Collection homepage: the 3 "Collection" sections in the left nav should be left aligned
- Remove the gray line between collections sections in left nav
- A little more breathing room in right margin of left nav and left margin of body and inbetween the gray lines and the section headers in metadata
image

**Comment by marlo-longley** [comment]
@astridu thanks for the review! I will address these and let you know when it's up.

**Comment by astridu** [comment]
Sorry, one more small thing, can you put a little space between these buttons:
Current
image
Desired
image

**Comment by astridu** [comment]
And these as well:
Current
image

Desired
image

thank you thank you thank you!

**Comment by marlo-longley** [comment]
@astridu Thanks. For that download button, I didn't change it because we actually have the download functionality (you can download a PDF or a finding aid) but we don't have Request functionality.

**Comment by astridu** [comment]
@marlo-longley Sounds good. Just the spacing inbetween the buttons. I think your font sizes look fine. Thank you!

**Pull request merged**
