### PR TITLE
Replace image carousel with single featured image

### LINKED ISSUE #540: Landing page should feature a single image rather than multiple
Change the landing page to display only one of the featured images per page load.

### PR DESCRIPTION
**Pull request by marlo-longley**
Closes #540 

The image is randomly selected with the `.sample` method on each page load. 
Heads up, I did `rake assets:clobber` and hard refreshed before the CSS looked right.

Screenshot 2024-04-19 at 16 11 11

### CODE REVIEW

**Comment by taylor-steve** [comment]
@marlo-longley this displays the image at smaller viewport sizes, where before we weren't. Is this intentional? I'd be fine changing it, although the images with the more portrait aspect ratios (that I randomly selected!) appear huge at those sizes.

I didn't know about `.sample`, Ruby has everything!

**Comment by marlo-longley** [comment]
Oh great point. Thank you for checking out mobile. I can remove the image at smaller sizes !

**Comment by marlo-longley** [comment]
Alright! @taylor-steve I adjusted the mobile styles to remove the image on smaller screens, and generally tried to improve the mobile alignment:

before

Screenshot 2024-04-23 at 09 53 38

after
Screenshot 2024-04-23 at 09 52 11

**Review by taylor-steve — APPROVED** [review]

**Comment by marlo-longley** [comment]
@taylor-steve conflict resolved

**Pull request merged**
